version: 2
jobs:
  build:
    docker:                              # CircleCI tags: https://circleci.com/docs/2.0/docker-image-tags.json
      - image: circleci/node:10-browsers # Node tags: https://nodejs.org/en/download/releases/
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test && npm run coverage